export ROOT_INCLUDE_PATH=${LARLITE_BASEDIR}/core
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARCV_BASEDIR}/larcv/core/PyUtil
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARCV_BASEDIR}/larcv/core/CPPUtil
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARCV_BASEDIR}/larcv/core/Processor
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARCV_BASEDIR}/larcv/core/ROOTUtil
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARCV_BASEDIR}/larcv/app/ImageMod
export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${LARLITE_BASEDIR}/larcv/core/DataFormat:${LARCV_BASEDIR}/larcv/core/Base
